translate-agent/mf2

- ast.go
- parse.go
- parse_test.go
AST to MF2 string representation
~**Waiting for #5**~
> AST string representation

- parse.go
- Added error handling for unexpected tokens in parsers
- Added descriptive error type, that shows, expected tokens vs actual one
- Fixed exhaustive linter
- Add some other errors, for example, cant convert str to float64, and multiple variables/literals, where only one is expected
- Removed TODO's
> Parser Error Handling

- README.md
- lex.go
> Update MF2 Syntax to 2023-12-18 version

- .golangci.yml
- lex.go
- lex_test.go
- parse.go
> Lexer: Break down itemKeyword into multiple items

- README.md
- parse/ast.go
- parse/lex.go
- parse/lex_test.go
- parse/parse.go
- parse/parse_test.go
- Lexer ✅ 
- AST/Parser ✅ 
- Builder ❌
> Update MF2 definition to 2024-01-24 version

- builder.go
- parse/ast.go
- parse/parse.go
- parse/parse_test.go
Remove Expression interface, and combine concrete structs into one
> Reduce AST complexity: Expression

- README.md
- builder.go
- parse/ast.go
- parse/lex.go
- template/registry/datetime.go
- template/registry/number.go
- template/registry/string.go
- template/template.go
- template/template_test.go
Fixes #57. Additionally, I did some TIDYING.
> #57 - update to the latest ABNF definition

- .github/workflows/ci.yaml
- .gitmodules
- wg_test.go
* run MF2 WG tests
* use git submodule for MF2 WG to ease tracking WG changes
> run MF2 WG tests; use git submodule for MF2 WG

- parse/lex.go
- parse/parse.go
Pass `missing space {42:func}`. #60
> #60 - pass MF2 WG missing space in func test

- template/template.go
Pass the following MF2 WG core test. Relates to #60 
```
.local $foo = {|bar|} {{bar {$foo}}}
```
> #60 - pass ".local $foo = {|bar|} {{bar {$foo}}}" MF2 WG core test

- parse/parse.go
- template/template.go
- template/template_test.go
> #60 - pass ".foo {42} {{bar}}" MF2 WG core test

- mf2wg_test.go
- template/template.go
* add missing MF2 errors
* enable tests that pass now
> add missing MF2 errors

- mf2wg_test.go
- template/template.go
Pass string matcher test with quoted literal.
> Unquote quoted literals

- mf2wg_test.go
- parse/ast.go
- parse/parse.go
- parse/parse_test.go
- template/template.go
Also, I renamed match statements with selectors.
> 146 - pass MF2 WG tests that return ErrVariantKeyMismatch

- mf2wg_test.go
- parse/lex.go
- parse/lex_test.go
Lex number literal at the end of lexName()
> Pass MF2WG number test

- mf2wg_test.go
- template/registry.go
- template/registry_number.go
- template/registry_number_test.go
Try to parse strings into Int or Float when needed in number functions
> 161 pass mf2wg number test hello |42| number minimumfractiondigits=|2|

- template/registry_string.go
- template/template.go
- template/template_test.go
Input already provides value formatting in the _:string_ func.
> tidy :string func

- errors.go
- mf2wg_test.go
- template/template.go
Search for duplicate variants before matching anything
> Handle duplicate variant errors

- parse/lex.go
- parse/lex_test.go
- parse/parse_test.go
Use `strings.Builder` where possible
> Refactor lexer

- template/template.go
```go
// replace
func matchSelectorKeys(rv any, keys []string) []string
// with
func matchSelectorKeys(selector *ResolvedValue, keys []string) []string
```
```console
$ benchstat a.txt b.txt
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/template
Template_Sprint-12   2.477µ ± 1%   2.433µ ± 1%  -1.78% (p=0.001 n=10)
│     B/op     │     B/op      vs base               │
Template_Sprint-12   4.391Ki ± 0%   4.297Ki ± 0%  -2.14% (p=0.000 n=10)
│   a.txt    │               b.txt               │
│ allocs/op  │ allocs/op   vs base               │
Template_Sprint-12   88.00 ± 0%   86.00 ± 0%  -2.27% (p=0.000 n=10) …
```
> refactor select key
