.github/workflows/ci.yaml
README.md

Display CI badge in README - https://github.com/expect-digital/go-mf2/tree/display-badge

display CI badge

---

.golangci.yml
lex.go
lex_test.go

We run `golangci-lint` without conf.
I added it and rectified all lint issues.

add golangci-lint conf

---

go.mod
go.sum
template/example_test.go
template/registry/number.go
template/registry/number_test.go
template/registry/registry.go
template/registry/string.go
template/registry/string_test.go
template/template.go
template/template_test.go

Initial implementation design for integrating functions (default and custom) into the template:
Currently, only two functions have been included:
- `string`
- `number` (though not fully implemented due to complexity in accommodating all options

Design And Initial Implementation of Default Function Registry

---

parse/lex.go
parse/lex_test.go
wg_test.go

part of #60
* fix `{{}}}` test from MF2 WG test cases
* simplify lexPattern

#60 - pass MF2 WG unescaped curly bracket test

---

wg_test.go

All MF2 WG `syntax errors` tests pass now. #60

enable MF2 WG syntax errors tests

---

.golangci.yml
parse/parse.go
template/example_test.go
template/registry/datetime.go
template/registry/datetime_test.go
template/registry/number.go
template/registry/number_test.go
template/registry/registry.go
template/registry/string.go
template/registry/string_test.go
template/template.go
template/template_test.go
wg_test.go

Pass the following MF2 WG test. Relates to #60.
```json
{
"src": "{$one} et {$two}",
"locale": "fr",
"params": { "one": 1.3, "two": 4.2 },
"exp": "1,3 et 4,2"
}
```

#60 - pass "{$one} et {$two}" MF2 WG core test

---

.github/workflows/ci.yaml
README.md
builder_test.go
go.mod
parse/lex_test.go
parse/parse.go
parse/parse_test.go
template/registry/datetime_test.go
template/registry/number_test.go
template/registry/string_test.go
template/template_test.go
wg_test.go

* Support the latest golang 1.22+
* Drop the support of the older golang versions
It simplifies error handling like `errorsJoin()` etc.

update min go version to v1.22

---

template/template.go
template/template_test.go
wg_test.go

Pass the following MF2 WG test.
```json
{
"src": "foo {&private}",
"exp": "foo {&}",
"parts": [
{ "type": "literal", "value": "foo " },
{ "type": "fallback", "source": "&" }
],
"errors": [{ "type": "unsupported-annotation" }]
}
```

#60 - pass "foo {&private}" MF2 WG core test

---

template/template.go

Pass the following MF2 WG test
```json
{
"src": "foo {?reserved @a @b=$c}",
"exp": "foo {?}",
"parts": [
{ "type": "literal", "value": "foo " },
{ "type": "fallback", "source": "?" }
],
"errors": [{ "type": "unsupported-annotation" }]
},
```

#60 - pass "foo {?reserved @a @b=$c}" MF2 WG core test

---

parse/ast.go

Pass the following MF2 WG test:
```json
{ "src": "hello {||}", "exp": "hello " },
```

#60 - pass "hello {||}" MF2 WG core test

---

parse/ast.go
parse/lex.go
parse/lex_test.go
parse/parse.go

Pass the following MF2 WG test:
```json
{
"src": "{/tag foo=bar}",
"exp": "",
"parts": [
{
"type": "markup",
"kind": "close",
"name": "tag",
"options": { "foo": "bar" }
}
]
},
```

60 pass "{/tag foo=bar}"

---

parse/lex.go
parse/lex_test.go
wg_test.go

Pass the following MF2 WG test:
```json
{
"src": "{#tag a:foo=|foo| b:bar=$bar}",
"params": { "bar": "b a r" },
"exp": "",
"parts": [
{
"type": "markup",
"kind": "open",
"name": "tag",
"options": { "a:foo": "foo", "b:bar": "b a r" }
}
]
},
```

#60 - pass "{#tag a:foo=|foo| b:bar=$bar}" MF2 WG core test

---

README.md
template/registry/number.go
template/registry/number_test.go

The maximum number of fraction digits to use.
The default for plain number formatting is the larger of minimumFractionDigits and 3.
The default for percent formatting is the larger of minimumFractionDigits and 0.

add maximumFractionDigits option to number func

---

template/template.go

Pass FM2 WG function test
```json
{
"src": "{$x :datetime}",
"exp": "{$x}",
"params": { "x": true },
"errors": [{ "type": "bad-input" }]
}
```

#60 - pass "{$x :datetime}" MF2 WG function test

---

mf2wg_test.go

Previously all MF2WG tests were skipped - incorrect location of `t.Skip()`,  move it to the subtest.

fix skipped MF2WG tests

---

parse/lex.go
parse/parse.go
parse/parse_test.go

I ignored the errors in `validate()` functions in `ast.go`.
Very likely I'll apply verification at the point of building AST, and remove the `validate()` functions.

120 - improve error messaging in parse package

---

builder/builder_test.go
errors.go
mf2wg_test.go
parse/parse_test.go
template/example_test.go
template/registry_datetime.go
template/registry_datetime_test.go
template/registry_number.go
template/registry_string_test.go
template/registry_test.go
template/template.go
template/template_test.go

* ensured errors are the same as in the MF2 spec
* wrapped all error strings with single quotes in the unit tests to make reading easier in the terminal.

137 - sync errors definition with MF2 errors spec

---

mf2wg_test.go
template/template.go

Collecting non-critical errors, e.g., when input variable not defined, it generates an error `unresolved-variable` but also executes the template using some fallback value (nil).

Pass MF2WG string test #02

---

builder/builder.go
mf2wg_test.go
parse/ast.go
parse/parse.go
parse/parse_test.go
template/template.go

Originally `NumberLiteral` was float64 type, but the documentation says: 
> [..] a literal value with no annotation is always treated as a string. To represent values that are not strings as a literal, an annotation needs to be provided[.]
https://github.com/unicode-org/message-format-wg/blob/132d9c326271ce552cb485e07223f592fa51593e/spec/formatting.md?plain=1#L157-L160
Now the annotation function has to convert the operand into numeric type if needed.

Formatted zeros

---

mf2wg_test.go
parse/lex.go
parse/lex_test.go
parse/parse.go
parse/parse_test.go

* lex the start
* handle whitespaces at the beginning and the end
Fixes #211 
```
➜  parse git:(211-lex-start) ✗ benchstat a.txt b.txt
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/parse
ComplexMessage_String-12   3.078µ ± 1%   3.134µ ± 1%  +1.84% (p=0.000 n=10)
Lex-12                     1.503µ ± 0%   1.581µ ± 1%  +5.19% (p=0.000 n=10)
Parse-12                   3.199µ ± 1%   3.334µ ± 2%  +4.22% (p=0.000 n=10)
geomean                    2.455µ        2.547µ       +3.74%
│    a.txt     │                 b.txt                 │
│     B/op     │     B/op      vs base                 │
ComplexMessage_String-12   20.33Ki ± 0%   20.33Ki ± 0%       ~ (p=1.000 n=10) …
```

211 - lex start

---

.github/workflows/ci.yaml
mf2wg_test.go

Also, log MF2 test description.

bump golangci-lint to v1.60.2

---

.github/workflows/ci.yaml
.gitignore

Also, ignore _*.txt_ files - output of _go test -bench_.

bump golangci-lint to v1.60.3

---

template/registry_string_test.go
template/template.go

```console
$ benchstat a.txt b.txt                             
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/template
Template_Sprint-12   2.703µ ± 0%   2.646µ ± 1%  -2.09% (p=0.000 n=10)
│     B/op     │     B/op      vs base               │
Template_Sprint-12   4.588Ki ± 0%   4.578Ki ± 0%  -0.21% (p=0.000 n=10)
│   a.txt    │               b.txt               │
│ allocs/op  │ allocs/op   vs base               │
Template_Sprint-12   93.00 ± 0%   92.00 ± 0%  -1.08% (p=0.000 n=10)
```

format any type

---

mf2wg_test.go
parse/parse.go

Some of whitespaces in MF2 now are mandatory.

Mandatory whitespaces

---

parse/lex.go
parse/lex_test.go

```console
$ benchstat a.txt b.txt                             
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/parse
ComplexMessage_String-12   4.169µ ± 1%   4.175µ ± 1%       ~ (p=0.698 n=10)
Lex-12                     2.006µ ± 0%   1.931µ ± 1%  -3.74% (p=0.000 n=10)
Parse-12                   3.833µ ± 0%   3.737µ ± 1%  -2.53% (p=0.002 n=10)
geomean                    3.177µ        3.111µ       -2.06%
│    a.txt     │                 b.txt                 │
│     B/op     │     B/op      vs base                 │
ComplexMessage_String-12   27.16Ki ± 0%   27.16Ki ± 0%       ~ (p=1.000 n=10) ¹
Lex-12                       856.0 ± 0%     856.0 ± 0%       ~ …
```

lex name and identifier

---

parse/ast.go

```console
$ benchstat a.txt b.txt                                           
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/parse
│    sec/op    │   sec/op     vs base                │
ComplexMessage_String-12   4073.5n ± 1%   883.9n ± 1%  -78.30% (p=0.000 n=10)
│    a.txt     │               b.txt                │
│     B/op     │    B/op     vs base                │
ComplexMessage_String-12   27816.0 ± 0%   776.0 ± 0%  -97.21% (p=0.000 n=10)
│   a.txt    │               b.txt                │
│ allocs/op  │ allocs/op   vs base                │
ComplexMessage_String-12   61.00 ± 0%   33.00 ± 0%  -45.90% (p=0.000 n=10)
```

re-use text escaper

---

parse/lex.go
parse/lex_test.go

```console
$ benchstat a.txt b.txt      
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/parse
│    sec/op    │   sec/op     vs base                │
ComplexMessage_String-12    879.8n ± 1%   894.2n ± 1%   +1.64% (p=0.000 n=10)
Lex-12                     1308.0n ± 1%   974.2n ± 1%  -25.52% (p=0.000 n=10)
Parse-12                    3.058µ ± 0%   2.700µ ± 0%  -11.69% (p=0.000 n=10)
geomean                     1.521µ        1.330µ       -12.56%
│    a.txt     │                 b.txt                  │
│     B/op     │     B/op      vs base                  │
ComplexMessage_String-12     776.0 ± 0%     776.0 ± 0%        ~ (p=1.000 n=10) ¹
Lex-12                       656.0 ± 0%     112.0 ± 0%  -82.93% (p=0.000 …
```

improve lexing unquoted and number literals

---

template/template.go

Currently, ALL variant keys are ALWAYS passed to selectKey().
We only want to pass variant (unique) keys for a particular selector.
```console
$ benchstat a.txt b.txt                       
goos: darwin
goarch: arm64
pkg: go.expect.digital/mf2/template
Template_Sprint-12   2.428µ ± 0%   2.333µ ± 0%  -3.91% (p=0.000 n=10)
│     B/op     │     B/op      vs base               │
Template_Sprint-12   4.297Ki ± 0%   4.141Ki ± 0%  -3.64% (p=0.000 n=10)
│   a.txt    │               b.txt               │
│ allocs/op  │ allocs/op   vs base               │
Template_Sprint-12   86.00 ± 0%   82.00 ± 0%  -4.65% (p=0.000 n=10) …
```

use variant keys for particular selector
